# Balint's Numpy assignment












In [1]:
import numpy as np
import pandas as pd

1- Create three lists representing house features, each list containing ten values. The first one for the house's size in square meters, the second one for rooms and last for price. Then, create an array combining these lists.

In [102]:
size = [130, 210, 870, 55, 80, 90, 190, 330, 90, 110]
rooms = [2, 3, 7, 1, 2, 3, 5, 6, 2, 3]
price = [100, 150, 700, 110, 130, 190, 450, 290, 320, 625]

In [103]:
my_array = np.array([size, rooms, price])
print(my_array)

[[130 210 870  55  80  90 190 330  90 110]
 [  2   3   7   1   2   3   5   6   2   3]
 [100 150 700 110 130 190 450 290 320 625]]


2- Transpose the array you have created, so that every line can represent features of one house.

In [104]:
transposed = my_array.T
print(transposed)

[[130   2 100]
 [210   3 150]
 [870   7 700]
 [ 55   1 110]
 [ 80   2 130]
 [ 90   3 190]
 [190   5 450]
 [330   6 290]
 [ 90   2 320]
 [110   3 625]]


3- Display the shape of the array and explain what it means.
For the following assignment, you are going to use Earthquakes dataset.

In [105]:
my_array.shape

(3, 10)

The .shape feature displays the number of rows (3) and the number of columns (10) of the array

4- Load the Earthquakes dataset. Export the dataset to an array as you covered in the previous lesson.

In [106]:
# Import the csv file from my computer
data = pd.read_csv(r'C:\Users\BalintStewart\OneDrive - Health Data Research\Desktop\Magnimind\Numpy.13\earthquakes1970-2014.csv')
data.head()

DateTime  Latitude  Longitude  Depth  Magnitude MagType  \
0  1970/01/04 17:00:40.20    24.139    102.503   31.0        7.5      Ms   
1  1970/01/06 05:35:51.80    -9.628    151.458    8.0        6.2      Ms   
2  1970/01/08 17:12:39.10   -34.741    178.568  179.0        6.1      Mb   
3  1970/01/10 12:07:08.60     6.825    126.737   73.0        6.1      Mb   
4  1970/01/16 08:05:39.00    60.280   -152.660   85.0        6.0      ML   

   NbStations  Gap  Distance  RMS Source       EventID  
0        90.0  NaN       NaN  0.0    NEI  1.970010e+09  
1        85.0  NaN       NaN  0.0    NEI  1.970011e+09  
2        59.0  NaN       NaN  0.0    NEI  1.970011e+09  
3        91.0  NaN       NaN  0.0    NEI  1.970011e+09  
4         0.0  NaN       NaN  NaN     AK           NaN

In [107]:
data.dtypes

DateTime       object
Latitude      float64
Longitude     float64
Depth         float64
Magnitude     float64
MagType        object
NbStations    float64
Gap           float64
Distance      float64
RMS           float64
Source         object
EventID       float64
dtype: object

In [108]:
# Export the dataset to an array. This array includes non-numeric data (needed for slicing exercise 5 below)
array = data.to_numpy()
array

array([['1970/01/04 17:00:40.20', 24.1389999999999, 102.503, ..., 0.0,
        'NEI', 1970010440.0],
       ['1970/01/06 05:35:51.80', -9.628, 151.458, ..., 0.0, 'NEI',
        1970010640.0],
       ['1970/01/08 17:12:39.10', -34.741, 178.568, ..., 0.0, 'NEI',
        1970010840.0],
       ...,
       ['2013/12/17 23:38:08.10', 20.7635, 146.759899999999, ..., 0.74,
        'us', 2013121720.0],
       ['2014/01/01 16:03:28.89', -13.8779, 167.2434, ..., 0.67, 'us',
        2014010120.0],
       ['2014/01/13 04:01:04.69', 19.0014, -66.8478, ..., 1.42, 'us',
        2014011320.0]], dtype=object)

5- Slice first 20 rows and column numbers 3, 5, 6, 7, 12. Then, assign the array you sliced to a variable.

In [109]:
slice = array[0:20, [2,4,5,6,11]] # note zero indexing
print(slice)

[[102.503 7.5 'Ms' 90.0 1970010440.0]
 [151.458 6.2 'Ms' 85.0 1970010640.0]
 [178.568 6.1 'Mb' 59.0 1970010840.0]
 [126.736999999999 6.1 'Mb' 91.0 1970011040.0]
 [-152.66 6.0 'ML' 0.0 nan]
 [-177.348999999999 6.5 'Mb' 175.0 1970012040.0]
 [142.966 6.4 'Ms' 199.0 1970012040.0]
 [-104.298 6.6 'Ms' 140.0 1970012140.0]
 [166.37 6.4 'Ms' 91.0 1970012640.0]
 [-99.48399999999991 6.5 'Ms' 100.0 1970020440.0]
 [122.117 6.6 'Ms' 94.0 1970020540.0]
 [100.775 6.1 'Ms' 57.0 1970020640.0]
 [103.031 6.0 'Ms' 94.0 1970022440.0]
 [-179.5898 6.0 'ML' 0.0 nan]
 [-175.039999999999 6.1 'ML' 0.0 nan]
 [143.706999999999 6.2 'Ms' 82.0 1970030440.0]
 [168.603 6.5 'Ms' 61.0 1970030940.0]
 [148.87 6.0 'Mb' 65.0 1970031040.0]
 [-153.97 6.5 'ML' 0.0 nan]
 [-69.49899999999991 6.0 'Mb' 118.0 1970031540.0]]


6- Display the row numbers where last values are equal to 4.5 or higher.
(Balint's comment - does 'last values' mean the value in the last column of the array, which is the EventID? Seems a little odd...)

In [110]:
# Select the last column of the array
last_col = array[:, -1]

# use np.where function to find rows where condition is true
row_indices = np.where(last_col >= 4.5)
print(row_indices)


(array([   0,    1,    2, ..., 5301, 5302, 5303]),)


C:\Users\BalintStewart\AppData\Local\Temp\ipykernel_16232\2458065512.py:5: RuntimeWarning: invalid value encountered in greater_equal
  row_indices = np.where(last_col >= 4.5)


7- Assign 1 to first row.

In [111]:
array[0] = 1
print(array)

[[1 1 1 ... 1 1 1]
 ['1970/01/06 05:35:51.80' -9.628 151.458 ... 0.0 'NEI' 1970010640.0]
 ['1970/01/08 17:12:39.10' -34.741 178.568 ... 0.0 'NEI' 1970010840.0]
 ...
 ['2013/12/17 23:38:08.10' 20.7635 146.759899999999 ... 0.74 'us'
  2013121720.0]
 ['2014/01/01 16:03:28.89' -13.8779 167.2434 ... 0.67 'us' 2014010120.0]
 ['2014/01/13 04:01:04.69' 19.0014 -66.8478 ... 1.42 'us' 2014011320.0]]


8- Save the final state of the array to disk. You are going to use this in the next assignment.

In [112]:
# Save the array to a file
np.save(r'C:\Users\BalintStewart\OneDrive - Health Data Research\Desktop\Magnimind\Numpy.13\assignment_array.npy', array)

9- Load the array you saved in the previous lesson from the disk.

In [113]:
mod_array = np.load(r'C:\Users\BalintStewart\OneDrive - Health Data Research\Desktop\Magnimind\Numpy.13\assignment_array.npy', allow_pickle= True) # allow_pickle needed because of array containing python objects liek datetime, strings


10- Display the mean and the standard deviation for each column.


In [114]:
# Need to first remove non-numeric columns to run aggregate functions on all the columns
num_array = mod_array[:,[1,2,3,4,6,7,8,11]]
num_array


array([[1, 1, 1, ..., 1, 1, 1],
       [-9.628, 151.458, 8.0, ..., nan, nan, 1970010640.0],
       [-34.741, 178.568, 179.0, ..., nan, nan, 1970010840.0],
       ...,
       [20.7635, 146.759899999999, 16.06, ..., 14.0, 4.0, 2013121720.0],
       [-13.8779, 167.2434, 187.0, ..., 14.0, 4.0, 2014010120.0],
       [19.0014, -66.8478, 28.0, ..., 21.0, 1.0, 2014011320.0]],
      dtype=object)

In [115]:
mean_per_column = np.nanmean(num_array, axis=0) # no.nanmean ignores NaN values in the column
mean_per_column

array([2.5859975490196043, 44.62208761312208, 74.26238122171952,
       6.3678883861236075, 301.7569523809524, 48.820809248554916,
       6.573099415204679, 1979933208.4465852], dtype=object)

In [116]:
std_per_column = np.nanstd(num_array, axis = 0) # this throws an error 
std_per_column

TypeError: loop of ufunc does not support argument 0 of type float which has no callable sqrt method

11- Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be done in one line of code.)


In [120]:
new_array = num_array - np.array([1, 25, 25, 10, 4,0,0,0]) # This subtracts 1 from each row in col 1, 25 from each row in col 2 etc. There are 8
new_array

array([[0, -24, -24, ..., 1, 1, 1],
       [-10.628, 126.458, -17.0, ..., nan, nan, 1970010640.0],
       [-35.741, 153.568, 154.0, ..., nan, nan, 1970010840.0],
       ...,
       [19.7635, 121.75989999999899, -8.940000000000001, ..., 14.0, 4.0,
        2013121720.0],
       [-14.8779, 142.2434, 162.0, ..., 14.0, 4.0, 2014010120.0],
       [18.0014, -91.8478, 3.0, ..., 21.0, 1.0, 2014011320.0]],
      dtype=object)

12- Multiply each element by 2. (Remember it can be done in one line of code.)

In [122]:
times_two = new_array * 2
times_two

array([[0, -48, -48, ..., 2, 2, 2],
       [-21.256, 252.916, -34.0, ..., nan, nan, 3940021280.0],
       [-71.482, 307.136, 308.0, ..., nan, nan, 3940021680.0],
       ...,
       [39.527, 243.51979999999799, -17.880000000000003, ..., 28.0, 8.0,
        4026243440.0],
       [-29.7558, 284.4868, 324.0, ..., 28.0, 8.0, 4028020240.0],
       [36.0028, -183.6956, 6.0, ..., 42.0, 2.0, 4028022640.0]],
      dtype=object)